### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by xiaobailj** [Matthew-Lyu/Autonomous-Driving-Simulation-ROS#1]
There seems to be some issues with the lidar_simulation?

**Comment by Matthew-Lyu** [comment]
Laser is for local path planning, you can use your own binary map and scale it to the appropriate scale.

**Comment by xiaobailj** [comment]
After changing the radar detection range, it seems that the radar is unable to correctly detect obstacles in the map。
![Uploading Screenshot from 2024-03-28 16-18-30.png…]()

**Comment by Matthew-Lyu** [comment]
This radar needs to be adjusted according to the size and zoom ratio of the map. My parameters are for my demo map. You need to first modify the map zoom ratio in the yaml file according to your map, and then fine-tune the radar parameters.

**Comment by xiaobailj** [comment]
Based on your map and parameters, it is possible to plan normally, but the radar point cloud cannot be displayed, and the point cloud data is empty when viewed

**Comment by xiaobailj** [comment]
![Uploading Screenshot from 2024-03-28 17-26-35.png…]()

**Comment by Matthew-Lyu** [comment]
I understand what you mean. First, you need to realize that the radar is there for local path planning, and the condition for displaying the radar point cloud is the detection of obstacles. Currently, the resolution set in my map YAML file is 0.01, which means the resolution of the map is 0.01 meters per pixel. Since the parameters required by the background task of my project are fixed, my current simulation situation is equivalent to a small car (a cube with a collision volume) planning and controlling on a relatively open map. Because the path that the car can travel on the map is wide., global path planning plays the main role, and local path planning hardly plays a role. You can modify the resolution of the map to achieve the purpose of reducing the map size, so that when the path the small car can travel is relatively narrow, local path planning will come into play to avoid hitting obstacles. In this case, the radar point cloud you mentioned will be displayed.

image: 跑圈地图.jpg
resolution: 0.010000
origin: [0.0000, 0.0000, 0.00000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

**Comment by xiaobailj** [comment]
Okay, thank you for your guidance. The obstacle section under vehicle_simulation in the project seems to have not been used, but rather subscribed to obstacle information in the map through the Obstacle service?

**Comment by zhyocn** [comment]
sysu?
